name: database

services:
  db:
    image: mysql:8.4.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rekomendasiin
      MYSQL_USER: rekomendasiin
      MYSQL_PASSWORD: good_password
      MYSQL_ROOT_PASSWORD: good_password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
